version: '3'

services:
  postgres:
    image: 'postgres:14'
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/config:/etc/postgresql/conf.d
      - ./postgres/logs:/var/log/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Admin123
      - POSTGRES_HOST=postgres

  app:
    depends_on:
      - postgres
    build: .
    command: bash start
    volumes:
      - '.:/smartlocker'
    ports:
      - "80:3000"  # Mapear a porta 80 para acessar diretamente a aplicação Rails
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Admin123
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - FIRST_TIME_SETUP=true
      - RAILS_SERVE_STATIC_FILES=true
    networks:
      - default

networks:
  default:
    driver: bridge