version: '3.7'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      RAILS_ENV: production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DATABASE_URL: postgres://postgres:password@db:5432/smartlocker_production
      SECRET_KEY_BASE: "68ce970cdc45453c2a610c5854a727ebe61dfb1bae7622e5d8747072e46ca8aeb238ceadb13089b648beaab3a8d1dd5692c0c01e35adc3e053ac0736c0bcf641"
    depends_on:
      - db
    #command: bash -c "rm -rf tmp/pids/server.pid && bundle exec rails db:create db:migrate db:seed && bundle exec rails s -b '0.0.0.0'"
    command: ./entrypoint.sh

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartlocker_production
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
