version: '3'

services:
  postgres:
    image: 'postgres:14'
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/config:/etc/postgresql/conf.d
      - ./postgres/logs:/var/log/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Admin123
      - POSTGRES_HOST=postgres

  app:
    depends_on:
      - postgres
    build: .
    command: bash start
    volumes:
      - '.:/smartlocker'
    ports:
      - "3000:3000"  # Expondo a porta para permitir comunicação com o Nginx
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Admin123
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - FIRST_TIME_SETUP=true # Variável de ambiente para configuração inicial
      - RAILS_SERVE_STATIC_FILES=true
    networks:
      - default

  nginx:
    image: nginx
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"  # Porta pública para acessar a aplicação
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Montando o arquivo de configuração do Nginx
    networks:
      - default

networks:
  default:
    driver: bridge