default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["POSTGRES_USER"] %> #Funciona 
  password: <%= ENV["POSTGRES_PASSWORD"] %> #Funciona
  #username: smartlocker_user  # Alterado aqui
  #password: 1952  # Alterado aqui
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>

development:
  <<: *default
  database: smartlocker_development

test:
  <<: *default
  database: smartlocker_test

production:
  <<: *default
  database: smartlocker_production
